# Generated by Django 5.2.7 on 2025-12-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0013_alter_prestamo_fecha_devolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='status',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('DEVUELTO', 'Devuelto')], default='ACTIVO', max_length=12),
        ),
    ]
