# Generated by Django 5.2.7 on 2025-12-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0015_alter_alumno_id_alumno_alter_autor_id_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='id_historial',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
